<div class="span3">
	<div class="module">
		<div class="content">
			<ul class="side_nav">
				<li><a href="/Admin/"
					class="<?php if ($this->current == "main"){echo 'bold';}?>">Administration
						Main page</a></li>
				<li><a href="/Initialization/"
					class="<?php if ($this->current == "initialization"){echo 'bold';}?>">Platform
						Initialization</a></li>
				<li><a href="/Admin/monitoring/"
					class="<?php if ($this->current == "monitoring"){echo 'bold';}?>">Event
						Monitoring</a></li>
				<li><a href="/Admin/user/"
					class="<?php if ($this->current == "user"){echo 'bold';}?>">User
						Management</a></li>

			</ul>
		</div>
	</div>
</div>