<?php $this->pageTitle("Forgot Password"); ?>
<div class="module">
	<div class="heading">
		<h1>Reset your password</h1>
	</div>
	<div class="clr"></div>
	<div class="content">

<?php
if (count($this->messages) > 0) {
    foreach ($this->messages as $message) {
        ?>
<div class="alert-message success">
			<p><?php echo $this->escape($message);?></p>
		</div>
<?php
    }
}
?>
<?php echo $this->form;?>
</div>
</div>
