<?php $this->pageTitle("My Account"); ?>
<div class="module">
	<div class="heading">
		<h1>My Account</h1>
	</div>
	<div class="clr"></div>
	<div class="content">
		<table class="table table-bordered">
			<tr>
				<td width="150px"><h3>Account Settings</h3></td>
				<td>
					<ul>
						<li><a href="/My/profile">Change your profile (how others see you)</a></li>
						<li><a href="/My/password">Change your password</a></li>
					</ul>
				</td>
			</tr>
		</table>
	</div>
</div>
