<p>Hi there,</p>
<p>We recently received a request to change the password on your
	account.</p>
<p>If you requested this password change, please set a new password by
	following the link below:</p>
<p>
	<a href="<?php echo $this->link; ?>"><?php echo $this->link; ?></a>
</p>
<p>If you did not intend to change your password, just ignore this message.</p>
<?php
echo $this->partial('footer.phtml');
?>