<h1><?php echo $this->channel->getCustomer()->getName();?> has invited you to <?php echo $this->channel->getTitle();?>.</h1>

<p>Before you can start viewing the protected content for <?php echo $this->channel->getTitle();?> you must first create an account associated with <strong>this
		e-mail address</strong>. Please navigate to <a
		href="https://<?php echo $this->url;?>/register">https://<?php echo $this->url;?>/register</a>
	in order to create your account. <br /> Once you account has been
	created you will receive an activation email.
</p>