<?php $this->pageTitle("Assessment - Add a Question"); ?>
<div class="row">
	<div class="span12">
		<div class="head_main">
			<ul class="sbcbr_nav">
				<li><a
					href="/assessment/view/<?php echo $this->escape($this->assessment->getId());?>"><span>Back
							to Assessment</span> </a></li>

			</ul>
		</div>

		<div class="module">
			<div class="heading">
				<h2>Add a new True/False question</h2>
			</div>
			<div class="content">
				<?php echo $this->form;?>
			</div>
		</div>
	</div>
</div>
