<?php $this->pageTitle("Create an assessment"); ?>
<div class="row">
	<div class="span12">
		<div class="head_main">
			<ul class="sbcbr_nav">
				<li><a
					href="/course/curriculum/<?php echo $this->escape($this->courseId);?>"><span>Back
							to curriculum</span> </a></li>
			</ul>
		</div>
		<div class="module">
			<div class="heading">
				<h2>Add a new Assessment!</h2>
			</div>
			<div class="content">
				<?php echo $this->form;?>
			</div>
		</div>
	</div>
</div>
