<?php $this->pageTitle("Delete Assessment"); ?>
<div class="row">
	<div class="span12">
		<div class="head_main">
			<ul class="sbcbr_nav">
				<li><a
					href="/assessment/index/<?php echo $this->escape($this->assessment->getCourse()->getId());?>"><span>Back
							to assessment list</span> </a></li>

			</ul>
		</div>

		<div class="module">
			<div class="heading">
				<h2>Delete Assessment</h2>
			</div>
			<div class="content">
				<?php echo $this->form;?>
			</div>
		</div>
	</div>
</div>
