<?php $this->pageTitle("Assessments"); ?>
<div class="row">
	<div class="span12">
		<div class="module">
			<div class="heading">
				<h2>Assessments</h2>
			</div>
			<div class="clr"></div>
			<div class="content">
				<a class="btn btn-large btn-primary"
					href="/assessment/add/<?php echo $this->escape($this->courseId);?>">Create
					a new assessment</a>
				<table class="table table-bordered">
					<tr>
						<th colspan="3"></th>
						<th>Chapter</th>
						<th>Title</th>
						<th>Average Score</th>
					</tr>
<?php
foreach ($this->assessmentList as $key => $assessment) {
    echo $this->partial('partials/assessmentList.phtml', 
            array(
                    "assessment" => $assessment
            ));
}
?>
</table>
			</div>
		</div>

	</div>
</div>
