<?php $this->pageTitle("Initialization - Email Configuration"); ?>
<div class="row">
	<div class="span9">
		<div class="module">
			<div class="heading">
				<h2>System Configuration - Email</h2>
			</div>
			<div class="clr"></div>
			<div class="content">
				<p>Notifications are sent from the Digital Education Platform to
					users via a remote SMTP server. Many customers have an SMTP server
					onsite or use a remote email service such as Google Apps.</p>
				<?php echo $this->form;?>
			</div>
		</div>
	</div>
</div>
