<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!-- Consider adding an manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en">
<!--<![endif]-->
<head>
<meta charset="utf-8">
<!-- Use the .htaccess and remove these lines to avoid edge case issues.
       More info: h5bp.com/b/378 -->
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<?php echo $this->headTitle(); ?>
<meta name="description" content="">
<meta name="author" content="">

<!-- Mobile viewport optimized: j.mp/bplateviewport -->
<meta name="viewport" content="width=device-width,initial-scale=1">
<!-- <link rel="stylesheet" href="/css/style.css"> -->
<link rel="stylesheet" href="/css/libs/Twitter/2.0.4/bootstrap.min.css">
<link rel="stylesheet" href="/css/libs/Wijmo/2.1.0/wijmo-open.css">
<link rel="stylesheet" href="/css/styleim.css">
<link rel="stylesheet"
	href="/css/libs/JQueryUI/themes/smoothness/jquery-ui-1.8.16.custom.css">
<link rel="stylesheet"
	href="/css/libs/JQueryUI/themes/cupertino/jquery-ui-1.8.16.custom.css">

<!--  Dynamic Templates -->
<link rel="prefetch" type="application/x-handlebars-template"
	href="/templates/Site/Course/List.handlebars"
	data-template="Site_Course_List" />

<link rel="prefetch" type="application/x-handlebars-template"
	href="/templates/Site/Course/Questions.handlebars"
	data-template="Site_Course_Questions" />

<link rel="prefetch" type="application/x-handlebars-template"
	href="/templates/Site/Course/QuestionAnswers.handlebars"
	data-template="Site_Course_Question_Answers" />

<link rel="prefetch" type="application/x-handlebars-template"
	href="/templates/Site/Course/SettingsBasic.handlebars"
	data-template="Site_Course_Settings_Basic" />

<link rel="prefetch" type="application/x-handlebars-template"
	href="/templates/Site/Course/Announcements.handlebars"
	data-template="Site_Course_Announcements" />

<link rel="prefetch" type="application/x-handlebars-template"
	href="/templates/Site/Course/AnnouncementCreate.handlebars"
	data-template="Site_Course_Announcement_Create" />

<link rel="prefetch" type="application/x-handlebars-template"
	href="/templates/Site/Course/ContentSortable.handlebars"
	data-template="Site_Course_Content_Sortable" />

<link rel="prefetch" type="application/x-handlebars-template"
	href="/templates/Site/Course/Assessment/MultipleChoice.handlebars"
	data-template="Site_Course_Assessment_MultipleChoice" />

<!--  /Dynamic Templates -->
<script src="/js/libs/JQuery/1.7.1/jquery.min.js"></script>
<script src="/js/libs/JQueryUI/1.8.17/jquery-ui.min.js"></script>
<script src="/js/libs/jquery.ui.touch-punch.min.js"></script>
<script src="/js/libs/mjsarfatti/jquery.mjs.nestedSortable.js"></script>
<script src="/js/libs/json2.js"></script>
<script src="/js/libs/jquery.zend.jsonrpc.js"></script>
<script src="/js/libs/Wijmo/2.1.0/wijmo-open.min.js"></script>
<script type="text/javascript" src="/js/libs/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript"
	src="/js/libs/handlebars/handlebars-1.0.rc.1.js"></script>
<script type="text/javascript" src="/js/ThesisPlanet/dep.js"></script>
<script type="text/javascript" src="/js/ThesisPlanet/script.js"></script>

<!-- <script type="text/javascript" src="/js/libs/video.js/3.2.0/video.min.js"></script> -->
<?php

if ($this->dojo()->isEnabled()) {
	$this->dojo()->setLocalPath('/js/libs/dojo/dojo.js')->addStyleSheetModule('dijit.themes.tundra');
	echo $this->dojo();
}
?>
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="span12">
				<div class="header">
					<div class="logo">
						<?php
$service = new \App\Service\Configuration();

						?>
						<a href="/"><img alt=""
							src="<?php echo $service->acl_getImageUrl(); ?>" /></a>
					</div>
					<!-- logo close -->
					<div class="top_links">
      	<?php
$this->navigation()->setAcl(Zend_Registry::getInstance()->get('Zend_Acl'))->setRole(Zend_Auth::getInstance()->getIdentity());
if (\Zend_Auth::getInstance()->hasIdentity()) {

	$page = \Zend_Navigation_Page::factory((array('label' => 'Logout', 'uri' => '/logout')));
	$this->navigation()->addPage($page);
} else {
	$page = \Zend_Navigation_Page::factory((array('label' => 'Login', 'uri' => '/login')));
	$this->navigation()->addPage($page);
	$page = $this->navigation()->findOneBy('label', 'My Courses');
	$this->navigation()->removePage($page);
	$page = $this->navigation()->findOneBy('label', 'Discover Courses');
	$this->navigation()->removePage($page);
}
$menu = $this->navigation()->menu();
echo $menu;
		  ?>
      </div>
				</div>
			</div>
		</div>

		<!-- Content Section starts-->
		<div class="content">
                <?php if ($this->message !== null) : ?>
                <div class="row">
				<div class="span10 offset1">
					<div class="alert"><?php echo $this->message; ?></div>
				</div>
			</div>
                <?php endif; ?>
    			<?php echo $this->layout()->content; ?>
       </div>
		<!-- Content Section Ends-->
		<!--  FOOTER -->
		<div class="footer">
			<p>
				Powered By Education Platform. &copy; 2010 - 2013 - <a
					href="http://www.thesisplanet.com/" target="_blank">Thesis Planet</a>,
				LLC. All rights reserved.
			</p>
		</div>
		<!-- footer close -->
		<div class="clr"></div>
		<!--  END OF FOOTER -->
		<div class="clr"></div>
	</div>
</body>
</html>