<?php $this->pageTitle("File - View"); ?>
<script>
		$(function() {
			$( "#tabs" ).tabs();
		});
	</script>
<div class="row">
	<div class="span12">
		<div class="head_main">
			<h3><?php echo $this->file->getTitle();?></h3>
			<!-- heading close -->
			<ul class="sbcbr_nav">
				<li><a
					href="/course/view/<?php echo $this->file->getCourse()->getId();?>">&laquo;
						Go Back</a></li>
				<li><a
					href="<?php echo $this->service->acl_getDownloadUrl($this->file->getId(), null);?>">Download
						&raquo;</a></li>
				<li>
			<?php
if ($this->isComplete == true) {
    ?>  
<a class="isCompleted"
					onclick="markIncomplete('<?php echo $this->file->getCourse()->getId();?>','<?php echo $this->file->getId();?>');">Mark
						Incomplete</a>                  
<?php
} else {
    ?>
<a class="isCompleted"
					onclick="markComplete('<?php echo $this->file->getCourse()->getId();?>','<?php echo $this->file->getId();?>');">Mark
						Complete</a>
<?php
}
?>			
			
			</li>
			</ul>
		</div>
		<!-- navigation close -->
	</div>
</div>
<div class="row">
	<div class="span12">
		<div class="module">
			<div class="heading">
				<h1>File Details</h1>
			</div>
			<div class="content">
				<table class="table">
					<tr>
						<td width="30%"><b>Size</b></td>
						<td width="70%"><?php echo round($this->file->getOriginalSizeKB(), 2);?> Kb</td>
					</tr>
					<tr>
						<td><b>Extension</b></td>
						<td><?php echo $this->file->getOriginalExtension();?></td>
					</tr>
				</table>

				<a class="btn btn-large btn-primary"
					href="<?php echo $this->service->acl_getDownloadUrl($this->file->getId(), null);?>">Download
					File</a>
			</div>
		</div>
	</div>
</div>