<?php $this->pageTitle("Administration - Add User"); ?>
<div class="row">
	<div class="span12">
		<div class="module">
			<div class="heading">

				<h1>Add a new user</h1>
			</div>
			<div class="content">
				<p>
					Once you add a new user they will receive an email requesting that
					they activate their account.<br /> The individual will also need to
					know the password that you have provided so they can log in the
					first time. For security reasons we do not provide the password
					that you initially set.
				</p>
<?php
echo $this->form;
?>            
            </div>
		</div>
	</div>
</div>