<?php $this->pageTitle("Administration - Edit User"); ?>
<div class="row">
	<div class="span12">
		<div class="module">
			<div class="heading">
				<h2>Editing user ID: <?php echo $this->escape($this->id); ?></h2>
				<ul class="sbcbr_nav">
					<li><a href="/Admin/user"><span>Back to User management</span></a></li>
				</ul>
			</div>
			<div class="content">
			<?php
echo $this->form;
?>
			</div>
		</div>
	</div>
</div>

