<?php $this->pageTitle("Course - Invite someone!"); ?>
<div class="span9">
	<div class="module">
		<div class="heading">
			<h1>Invite someone to this course</h1>
		</div>
		<div class="clr"></div>
		<div class="content">
			<p>This individual will receive an e-mail invitation where they can,
				at their choice, subscribe to yoru course.</p>
<?php echo $this->form;?>
			</div>
	</div>
</div>




