<?php $this->pageTitle("Initialization - AWS Configuration"); ?>
<div class="row">
	<div class="span9">
		<div class="module">
			<div class="heading">
				<h2>Amazon Web Services</h2>
			</div>
			<div class="clr"></div>
			<div class="content">
				<p>
					You must first create an <a href="http://aws.amazon.com/"
						target="parent">Amazon Web Services</a> account in order to use
					the Digital Education Platform. Once you have created an account
					the following information is required for the Digital Education
					Platform to operate correctly. <br /> <br /> <strong> As a friendly
						reminder, please do not share your AWS account information with
						untrusted individuals or systems. Doing so may result in a
						security breach.</strong>

				</p>

			<?php echo $this->form;?>
			</div>
		</div>
	</div>
</div>
