<?php $this->pageTitle("Register an account"); ?>
<?php
if (count($this->messages)) :
    ?>
<ul id="messages">
<?php
    foreach ($this->messages as $message) :
        ?>
    <li><?php
        echo $this->escape($message);
        ?></li>
<?php
    endforeach
    ;
    ?>
</ul><?php endif;?>
<br />
<br />
<div class="row">
	<div class="span4 offset4">
		<div class="module">
			<div class="heading">
				<h2>Create a new account</h2>
			</div>
			<div class="clr"></div>
			<div class="content">
	<?php echo $this->form;?>
	</div>
		</div>
	</div>
</div>


