<?php $this->pageTitle("Accoutn Registered. Check your inbox!"); ?>
<div class="span11">
	<div class="module">
		<div class="heading">
			<h1>You are almost signed up!</h1>
		</div>
		<div class="clr"></div>
		<div class="content">
			<h2>It is time to check your inbox for a new e-mail.</h2>
			<p>In case you do not see it in your inbox, please check your spam
				folder. Sometimes it can take a couple of minutes for an e-mail to
				show up.</p>
		</div>
	</div>
</div>


